/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableMap
 */
package net.mayaan.util.datafix.fixes;

import com.google.common.collect.ImmutableMap;

public class StonecutterRecipeRenameFix {
    public static final ImmutableMap<String, String> RECIPE_RENAMES = ImmutableMap.builder().put((Object)"minecraft:chiseled_stone_bricks_stone_from_stonecutting", (Object)"minecraft:chiseled_stone_bricks_from_stone_stonecutting").put((Object)"minecraft:end_stone_brick_slab_from_end_stone_brick_stonecutting", (Object)"minecraft:end_stone_brick_slab_from_end_stone_bricks_stonecutting").put((Object)"minecraft:end_stone_brick_stairs_from_end_stone_brick_stonecutting", (Object)"minecraft:end_stone_brick_stairs_from_end_stone_bricks_stonecutting").put((Object)"minecraft:end_stone_brick_wall_from_end_stone_brick_stonecutting", (Object)"minecraft:end_stone_brick_wall_from_end_stone_bricks_stonecutting").put((Object)"minecraft:mossy_stone_brick_slab_from_mossy_stone_brick_stonecutting", (Object)"minecraft:mossy_stone_brick_slab_from_mossy_stone_bricks_stonecutting").put((Object)"minecraft:mossy_stone_brick_stairs_from_mossy_stone_brick_stonecutting", (Object)"minecraft:mossy_stone_brick_stairs_from_mossy_stone_bricks_stonecutting").put((Object)"minecraft:mossy_stone_brick_wall_from_mossy_stone_brick_stonecutting", (Object)"minecraft:mossy_stone_brick_wall_from_mossy_stone_bricks_stonecutting").put((Object)"minecraft:prismarine_brick_slab_from_prismarine_stonecutting", (Object)"minecraft:prismarine_brick_slab_from_prismarine_bricks_stonecutting").put((Object)"minecraft:prismarine_brick_stairs_from_prismarine_stonecutting", (Object)"minecraft:prismarine_brick_stairs_from_prismarine_bricks_stonecutting").put((Object)"minecraft:quartz_slab_from_stonecutting", (Object)"minecraft:quartz_slab_from_quartz_block_stonecutting").put((Object)"minecraft:stone_brick_walls_from_stone_stonecutting", (Object)"minecraft:stone_brick_wall_from_stone_stonecutting").build();
    public static final ImmutableMap<String, String> ADVANCEMENT_RENAMES = ImmutableMap.builder().put((Object)"minecraft:recipes/building_blocks/chiseled_stone_bricks_stone_from_stonecutting", (Object)"minecraft:recipes/building_blocks/chiseled_stone_bricks_from_stone_stonecutting").put((Object)"minecraft:recipes/building_blocks/end_stone_brick_slab_from_end_stone_brick_stonecutting", (Object)"minecraft:recipes/building_blocks/end_stone_brick_slab_from_end_stone_bricks_stonecutting").put((Object)"minecraft:recipes/building_blocks/end_stone_brick_stairs_from_end_stone_brick_stonecutting", (Object)"minecraft:recipes/building_blocks/end_stone_brick_stairs_from_end_stone_bricks_stonecutting").put((Object)"minecraft:recipes/decorations/end_stone_brick_wall_from_end_stone_brick_stonecutting", (Object)"minecraft:recipes/decorations/end_stone_brick_wall_from_end_stone_bricks_stonecutting").put((Object)"minecraft:recipes/building_blocks/mossy_stone_brick_slab_from_mossy_stone_brick_stonecutting", (Object)"minecraft:recipes/building_blocks/mossy_stone_brick_slab_from_mossy_stone_bricks_stonecutting").put((Object)"minecraft:recipes/building_blocks/mossy_stone_brick_stairs_from_mossy_stone_brick_stonecutting", (Object)"minecraft:recipes/building_blocks/mossy_stone_brick_stairs_from_mossy_stone_bricks_stonecutting").put((Object)"minecraft:recipes/building_blocks/mossy_stone_brick_wall_from_mossy_stone_brick_stonecutting", (Object)"minecraft:recipes/decorations/mossy_stone_brick_wall_from_mossy_stone_bricks_stonecutting").put((Object)"minecraft:recipes/building_blocks/prismarine_brick_slab_from_prismarine_stonecutting", (Object)"minecraft:recipes/building_blocks/prismarine_brick_slab_from_prismarine_bricks_stonecutting").put((Object)"minecraft:recipes/building_blocks/prismarine_brick_stairs_from_prismarine_stonecutting", (Object)"minecraft:recipes/building_blocks/prismarine_brick_stairs_from_prismarine_bricks_stonecutting").put((Object)"minecraft:recipes/building_blocks/quartz_slab_from_stonecutting", (Object)"minecraft:recipes/building_blocks/quartz_slab_from_quartz_block_stonecutting").put((Object)"minecraft:recipes/decorations/stone_brick_walls_from_stone_stonecutting", (Object)"minecraft:recipes/decorations/stone_brick_wall_from_stone_stonecutting").build();
}

