/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.mojang.serialization.MapCodec
 */
package net.minecraft.world.level.block;

import com.mojang.serialization.MapCodec;
import java.util.function.Function;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.level.block.AirBlock;
import net.minecraft.world.level.block.AmethystBlock;
import net.minecraft.world.level.block.AmethystClusterBlock;
import net.minecraft.world.level.block.AnvilBlock;
import net.minecraft.world.level.block.AttachedStemBlock;
import net.minecraft.world.level.block.AzaleaBlock;
import net.minecraft.world.level.block.BambooSaplingBlock;
import net.minecraft.world.level.block.BambooStalkBlock;
import net.minecraft.world.level.block.BannerBlock;
import net.minecraft.world.level.block.BarrelBlock;
import net.minecraft.world.level.block.BarrierBlock;
import net.minecraft.world.level.block.BaseCoralFanBlock;
import net.minecraft.world.level.block.BaseCoralPlantBlock;
import net.minecraft.world.level.block.BaseCoralWallFanBlock;
import net.minecraft.world.level.block.BeaconBlock;
import net.minecraft.world.level.block.BedBlock;
import net.minecraft.world.level.block.BeehiveBlock;
import net.minecraft.world.level.block.BeetrootBlock;
import net.minecraft.world.level.block.BellBlock;
import net.minecraft.world.level.block.BigDripleafBlock;
import net.minecraft.world.level.block.BigDripleafStemBlock;
import net.minecraft.world.level.block.BlastFurnaceBlock;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.BonemealableFeaturePlacerBlock;
import net.minecraft.world.level.block.BrewingStandBlock;
import net.minecraft.world.level.block.BrushableBlock;
import net.minecraft.world.level.block.BubbleColumnBlock;
import net.minecraft.world.level.block.BuddingAmethystBlock;
import net.minecraft.world.level.block.BushBlock;
import net.minecraft.world.level.block.ButtonBlock;
import net.minecraft.world.level.block.CactusBlock;
import net.minecraft.world.level.block.CactusFlowerBlock;
import net.minecraft.world.level.block.CakeBlock;
import net.minecraft.world.level.block.CalibratedSculkSensorBlock;
import net.minecraft.world.level.block.CampfireBlock;
import net.minecraft.world.level.block.CandleBlock;
import net.minecraft.world.level.block.CandleCakeBlock;
import net.minecraft.world.level.block.CarpetBlock;
import net.minecraft.world.level.block.CarrotBlock;
import net.minecraft.world.level.block.CartographyTableBlock;
import net.minecraft.world.level.block.CarvedPumpkinBlock;
import net.minecraft.world.level.block.CauldronBlock;
import net.minecraft.world.level.block.CaveVinesBlock;
import net.minecraft.world.level.block.CaveVinesPlantBlock;
import net.minecraft.world.level.block.CeilingHangingSignBlock;
import net.minecraft.world.level.block.ChainBlock;
import net.minecraft.world.level.block.ChestBlock;
import net.minecraft.world.level.block.ChiseledBookShelfBlock;
import net.minecraft.world.level.block.ChorusFlowerBlock;
import net.minecraft.world.level.block.ChorusPlantBlock;
import net.minecraft.world.level.block.CocoaBlock;
import net.minecraft.world.level.block.ColoredFallingBlock;
import net.minecraft.world.level.block.CommandBlock;
import net.minecraft.world.level.block.ComparatorBlock;
import net.minecraft.world.level.block.ComposterBlock;
import net.minecraft.world.level.block.ConcretePowderBlock;
import net.minecraft.world.level.block.ConduitBlock;
import net.minecraft.world.level.block.CopperBulbBlock;
import net.minecraft.world.level.block.CopperChestBlock;
import net.minecraft.world.level.block.CopperGolemStatueBlock;
import net.minecraft.world.level.block.CoralBlock;
import net.minecraft.world.level.block.CoralFanBlock;
import net.minecraft.world.level.block.CoralPlantBlock;
import net.minecraft.world.level.block.CoralWallFanBlock;
import net.minecraft.world.level.block.CrafterBlock;
import net.minecraft.world.level.block.CraftingTableBlock;
import net.minecraft.world.level.block.CreakingHeartBlock;
import net.minecraft.world.level.block.CropBlock;
import net.minecraft.world.level.block.CryingObsidianBlock;
import net.minecraft.world.level.block.DaylightDetectorBlock;
import net.minecraft.world.level.block.DecoratedPotBlock;
import net.minecraft.world.level.block.DetectorRailBlock;
import net.minecraft.world.level.block.DirtPathBlock;
import net.minecraft.world.level.block.DispenserBlock;
import net.minecraft.world.level.block.DoorBlock;
import net.minecraft.world.level.block.DoublePlantBlock;
import net.minecraft.world.level.block.DragonEggBlock;
import net.minecraft.world.level.block.DriedGhastBlock;
import net.minecraft.world.level.block.DropExperienceBlock;
import net.minecraft.world.level.block.DropperBlock;
import net.minecraft.world.level.block.DryVegetationBlock;
import net.minecraft.world.level.block.EnchantingTableBlock;
import net.minecraft.world.level.block.EndGatewayBlock;
import net.minecraft.world.level.block.EndPortalBlock;
import net.minecraft.world.level.block.EndPortalFrameBlock;
import net.minecraft.world.level.block.EndRodBlock;
import net.minecraft.world.level.block.EnderChestBlock;
import net.minecraft.world.level.block.EyeblossomBlock;
import net.minecraft.world.level.block.FarmlandBlock;
import net.minecraft.world.level.block.FenceBlock;
import net.minecraft.world.level.block.FenceGateBlock;
import net.minecraft.world.level.block.FireBlock;
import net.minecraft.world.level.block.FireflyBushBlock;
import net.minecraft.world.level.block.FlowerBedBlock;
import net.minecraft.world.level.block.FlowerBlock;
import net.minecraft.world.level.block.FlowerPotBlock;
import net.minecraft.world.level.block.FrogspawnBlock;
import net.minecraft.world.level.block.FrostedIceBlock;
import net.minecraft.world.level.block.FurnaceBlock;
import net.minecraft.world.level.block.GlazedTerracottaBlock;
import net.minecraft.world.level.block.GlowLichenBlock;
import net.minecraft.world.level.block.GrassBlock;
import net.minecraft.world.level.block.GrindstoneBlock;
import net.minecraft.world.level.block.HalfTransparentBlock;
import net.minecraft.world.level.block.HangingMossBlock;
import net.minecraft.world.level.block.HangingRootsBlock;
import net.minecraft.world.level.block.HayBlock;
import net.minecraft.world.level.block.HeavyCoreBlock;
import net.minecraft.world.level.block.HoneyBlock;
import net.minecraft.world.level.block.HopperBlock;
import net.minecraft.world.level.block.HugeMushroomBlock;
import net.minecraft.world.level.block.IceBlock;
import net.minecraft.world.level.block.InfestedBlock;
import net.minecraft.world.level.block.InfestedRotatedPillarBlock;
import net.minecraft.world.level.block.IronBarsBlock;
import net.minecraft.world.level.block.JigsawBlock;
import net.minecraft.world.level.block.JukeboxBlock;
import net.minecraft.world.level.block.KelpBlock;
import net.minecraft.world.level.block.KelpPlantBlock;
import net.minecraft.world.level.block.LadderBlock;
import net.minecraft.world.level.block.LanternBlock;
import net.minecraft.world.level.block.LavaCauldronBlock;
import net.minecraft.world.level.block.LayeredCauldronBlock;
import net.minecraft.world.level.block.LeafLitterBlock;
import net.minecraft.world.level.block.LecternBlock;
import net.minecraft.world.level.block.LeverBlock;
import net.minecraft.world.level.block.LightBlock;
import net.minecraft.world.level.block.LightningRodBlock;
import net.minecraft.world.level.block.LilyPadBlock;
import net.minecraft.world.level.block.LiquidBlock;
import net.minecraft.world.level.block.LoomBlock;
import net.minecraft.world.level.block.MagmaBlock;
import net.minecraft.world.level.block.MangroveLeavesBlock;
import net.minecraft.world.level.block.MangrovePropaguleBlock;
import net.minecraft.world.level.block.MangroveRootsBlock;
import net.minecraft.world.level.block.MossyCarpetBlock;
import net.minecraft.world.level.block.MudBlock;
import net.minecraft.world.level.block.MultifaceBlock;
import net.minecraft.world.level.block.MushroomBlock;
import net.minecraft.world.level.block.MyceliumBlock;
import net.minecraft.world.level.block.NetherFungusBlock;
import net.minecraft.world.level.block.NetherPortalBlock;
import net.minecraft.world.level.block.NetherRootsBlock;
import net.minecraft.world.level.block.NetherSproutsBlock;
import net.minecraft.world.level.block.NetherWartBlock;
import net.minecraft.world.level.block.NetherrackBlock;
import net.minecraft.world.level.block.NoteBlock;
import net.minecraft.world.level.block.NyliumBlock;
import net.minecraft.world.level.block.ObserverBlock;
import net.minecraft.world.level.block.PiglinWallSkullBlock;
import net.minecraft.world.level.block.PitcherCropBlock;
import net.minecraft.world.level.block.PlayerHeadBlock;
import net.minecraft.world.level.block.PlayerWallHeadBlock;
import net.minecraft.world.level.block.PointedDripstoneBlock;
import net.minecraft.world.level.block.PotatoBlock;
import net.minecraft.world.level.block.PowderSnowBlock;
import net.minecraft.world.level.block.PoweredBlock;
import net.minecraft.world.level.block.PoweredRailBlock;
import net.minecraft.world.level.block.PressurePlateBlock;
import net.minecraft.world.level.block.PumpkinBlock;
import net.minecraft.world.level.block.RailBlock;
import net.minecraft.world.level.block.RedStoneOreBlock;
import net.minecraft.world.level.block.RedStoneWireBlock;
import net.minecraft.world.level.block.RedstoneLampBlock;
import net.minecraft.world.level.block.RedstoneTorchBlock;
import net.minecraft.world.level.block.RedstoneWallTorchBlock;
import net.minecraft.world.level.block.RepeaterBlock;
import net.minecraft.world.level.block.RespawnAnchorBlock;
import net.minecraft.world.level.block.RootedDirtBlock;
import net.minecraft.world.level.block.RotatedPillarBlock;
import net.minecraft.world.level.block.SandBlock;
import net.minecraft.world.level.block.SaplingBlock;
import net.minecraft.world.level.block.ScaffoldingBlock;
import net.minecraft.world.level.block.SculkBlock;
import net.minecraft.world.level.block.SculkCatalystBlock;
import net.minecraft.world.level.block.SculkSensorBlock;
import net.minecraft.world.level.block.SculkShriekerBlock;
import net.minecraft.world.level.block.SculkVeinBlock;
import net.minecraft.world.level.block.SeaPickleBlock;
import net.minecraft.world.level.block.SeagrassBlock;
import net.minecraft.world.level.block.ShelfBlock;
import net.minecraft.world.level.block.ShortDryGrassBlock;
import net.minecraft.world.level.block.ShulkerBoxBlock;
import net.minecraft.world.level.block.SkullBlock;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.SlimeBlock;
import net.minecraft.world.level.block.SmallDripleafBlock;
import net.minecraft.world.level.block.SmithingTableBlock;
import net.minecraft.world.level.block.SmokerBlock;
import net.minecraft.world.level.block.SnifferEggBlock;
import net.minecraft.world.level.block.SnowLayerBlock;
import net.minecraft.world.level.block.SnowyBlock;
import net.minecraft.world.level.block.SoulFireBlock;
import net.minecraft.world.level.block.SoulSandBlock;
import net.minecraft.world.level.block.SpawnerBlock;
import net.minecraft.world.level.block.SpongeBlock;
import net.minecraft.world.level.block.SporeBlossomBlock;
import net.minecraft.world.level.block.StainedGlassBlock;
import net.minecraft.world.level.block.StainedGlassPaneBlock;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.StandingSignBlock;
import net.minecraft.world.level.block.StemBlock;
import net.minecraft.world.level.block.StonecutterBlock;
import net.minecraft.world.level.block.StructureBlock;
import net.minecraft.world.level.block.StructureVoidBlock;
import net.minecraft.world.level.block.SugarCaneBlock;
import net.minecraft.world.level.block.SweetBerryBushBlock;
import net.minecraft.world.level.block.TallDryGrassBlock;
import net.minecraft.world.level.block.TallFlowerBlock;
import net.minecraft.world.level.block.TallGrassBlock;
import net.minecraft.world.level.block.TallSeagrassBlock;
import net.minecraft.world.level.block.TargetBlock;
import net.minecraft.world.level.block.TestBlock;
import net.minecraft.world.level.block.TestInstanceBlock;
import net.minecraft.world.level.block.TintedGlassBlock;
import net.minecraft.world.level.block.TintedParticleLeavesBlock;
import net.minecraft.world.level.block.TntBlock;
import net.minecraft.world.level.block.TorchBlock;
import net.minecraft.world.level.block.TorchflowerCropBlock;
import net.minecraft.world.level.block.TransparentBlock;
import net.minecraft.world.level.block.TrapDoorBlock;
import net.minecraft.world.level.block.TrappedChestBlock;
import net.minecraft.world.level.block.TrialSpawnerBlock;
import net.minecraft.world.level.block.TripWireBlock;
import net.minecraft.world.level.block.TripWireHookBlock;
import net.minecraft.world.level.block.TurtleEggBlock;
import net.minecraft.world.level.block.TwistingVinesBlock;
import net.minecraft.world.level.block.TwistingVinesPlantBlock;
import net.minecraft.world.level.block.UntintedParticleLeavesBlock;
import net.minecraft.world.level.block.VaultBlock;
import net.minecraft.world.level.block.VineBlock;
import net.minecraft.world.level.block.WallBannerBlock;
import net.minecraft.world.level.block.WallBlock;
import net.minecraft.world.level.block.WallHangingSignBlock;
import net.minecraft.world.level.block.WallSignBlock;
import net.minecraft.world.level.block.WallSkullBlock;
import net.minecraft.world.level.block.WallTorchBlock;
import net.minecraft.world.level.block.WaterloggedTransparentBlock;
import net.minecraft.world.level.block.WeatheringCopperBarsBlock;
import net.minecraft.world.level.block.WeatheringCopperBulbBlock;
import net.minecraft.world.level.block.WeatheringCopperChainBlock;
import net.minecraft.world.level.block.WeatheringCopperChestBlock;
import net.minecraft.world.level.block.WeatheringCopperDoorBlock;
import net.minecraft.world.level.block.WeatheringCopperFullBlock;
import net.minecraft.world.level.block.WeatheringCopperGolemStatueBlock;
import net.minecraft.world.level.block.WeatheringCopperGrateBlock;
import net.minecraft.world.level.block.WeatheringCopperSlabBlock;
import net.minecraft.world.level.block.WeatheringCopperStairBlock;
import net.minecraft.world.level.block.WeatheringCopperTrapDoorBlock;
import net.minecraft.world.level.block.WeatheringLanternBlock;
import net.minecraft.world.level.block.WeatheringLightningRodBlock;
import net.minecraft.world.level.block.WebBlock;
import net.minecraft.world.level.block.WeepingVinesBlock;
import net.minecraft.world.level.block.WeepingVinesPlantBlock;
import net.minecraft.world.level.block.WeightedPressurePlateBlock;
import net.minecraft.world.level.block.WetSpongeBlock;
import net.minecraft.world.level.block.WitherRoseBlock;
import net.minecraft.world.level.block.WitherSkullBlock;
import net.minecraft.world.level.block.WitherWallSkullBlock;
import net.minecraft.world.level.block.WoolCarpetBlock;
import net.minecraft.world.level.block.piston.MovingPistonBlock;
import net.minecraft.world.level.block.piston.PistonBaseBlock;
import net.minecraft.world.level.block.piston.PistonHeadBlock;

public class BlockTypes {
    public static final MapCodec<Block> CODEC = BuiltInRegistries.BLOCK_TYPE.byNameCodec().dispatchMap(Block::codec, Function.identity());

    public static MapCodec<? extends Block> bootstrap(Registry<MapCodec<? extends Block>> registry) {
        Registry.register(registry, "block", Block.CODEC);
        Registry.register(registry, "air", AirBlock.CODEC);
        Registry.register(registry, "amethyst", AmethystBlock.CODEC);
        Registry.register(registry, "amethyst_cluster", AmethystClusterBlock.CODEC);
        Registry.register(registry, "anvil", AnvilBlock.CODEC);
        Registry.register(registry, "attached_stem", AttachedStemBlock.CODEC);
        Registry.register(registry, "azalea", AzaleaBlock.CODEC);
        Registry.register(registry, "bamboo_sapling", BambooSaplingBlock.CODEC);
        Registry.register(registry, "bamboo_stalk", BambooStalkBlock.CODEC);
        Registry.register(registry, "banner", BannerBlock.CODEC);
        Registry.register(registry, "barrel", BarrelBlock.CODEC);
        Registry.register(registry, "barrier", BarrierBlock.CODEC);
        Registry.register(registry, "base_coral_fan", BaseCoralFanBlock.CODEC);
        Registry.register(registry, "base_coral_plant", BaseCoralPlantBlock.CODEC);
        Registry.register(registry, "base_coral_wall_fan", BaseCoralWallFanBlock.CODEC);
        Registry.register(registry, "beacon", BeaconBlock.CODEC);
        Registry.register(registry, "bed", BedBlock.CODEC);
        Registry.register(registry, "beehive", BeehiveBlock.CODEC);
        Registry.register(registry, "beetroot", BeetrootBlock.CODEC);
        Registry.register(registry, "bell", BellBlock.CODEC);
        Registry.register(registry, "big_dripleaf", BigDripleafBlock.CODEC);
        Registry.register(registry, "big_dripleaf_stem", BigDripleafStemBlock.CODEC);
        Registry.register(registry, "blast_furnace", BlastFurnaceBlock.CODEC);
        Registry.register(registry, "brewing_stand", BrewingStandBlock.CODEC);
        Registry.register(registry, "brushable", BrushableBlock.CODEC);
        Registry.register(registry, "bubble_column", BubbleColumnBlock.CODEC);
        Registry.register(registry, "budding_amethyst", BuddingAmethystBlock.CODEC);
        Registry.register(registry, "bush", BushBlock.CODEC);
        Registry.register(registry, "button", ButtonBlock.CODEC);
        Registry.register(registry, "cactus", CactusBlock.CODEC);
        Registry.register(registry, "cactus_flower", CactusFlowerBlock.CODEC);
        Registry.register(registry, "cake", CakeBlock.CODEC);
        Registry.register(registry, "calibrated_sculk_sensor", CalibratedSculkSensorBlock.CODEC);
        Registry.register(registry, "campfire", CampfireBlock.CODEC);
        Registry.register(registry, "candle_cake", CandleCakeBlock.CODEC);
        Registry.register(registry, "candle", CandleBlock.CODEC);
        Registry.register(registry, "carpet", CarpetBlock.CODEC);
        Registry.register(registry, "carrot", CarrotBlock.CODEC);
        Registry.register(registry, "cartography_table", CartographyTableBlock.CODEC);
        Registry.register(registry, "cauldron", CauldronBlock.CODEC);
        Registry.register(registry, "cave_vines", CaveVinesBlock.CODEC);
        Registry.register(registry, "cave_vines_plant", CaveVinesPlantBlock.CODEC);
        Registry.register(registry, "ceiling_hanging_sign", CeilingHangingSignBlock.CODEC);
        Registry.register(registry, "chain", ChainBlock.CODEC);
        Registry.register(registry, "chest", ChestBlock.CODEC);
        Registry.register(registry, "chiseled_book_shelf", ChiseledBookShelfBlock.CODEC);
        Registry.register(registry, "chorus_flower", ChorusFlowerBlock.CODEC);
        Registry.register(registry, "chorus_plant", ChorusPlantBlock.CODEC);
        Registry.register(registry, "cocoa", CocoaBlock.CODEC);
        Registry.register(registry, "colored_falling", ColoredFallingBlock.CODEC);
        Registry.register(registry, "command", CommandBlock.CODEC);
        Registry.register(registry, "comparator", ComparatorBlock.CODEC);
        Registry.register(registry, "composter", ComposterBlock.CODEC);
        Registry.register(registry, "concrete_powder", ConcretePowderBlock.CODEC);
        Registry.register(registry, "conduit", ConduitBlock.CODEC);
        Registry.register(registry, "copper_bulb_block", CopperBulbBlock.CODEC);
        Registry.register(registry, "copper_chest", CopperChestBlock.CODEC);
        Registry.register(registry, "copper_golem_statue", CopperGolemStatueBlock.CODEC);
        Registry.register(registry, "coral", CoralBlock.CODEC);
        Registry.register(registry, "coral_fan", CoralFanBlock.CODEC);
        Registry.register(registry, "coral_plant", CoralPlantBlock.CODEC);
        Registry.register(registry, "coral_wall_fan", CoralWallFanBlock.CODEC);
        Registry.register(registry, "crafter", CrafterBlock.CODEC);
        Registry.register(registry, "crafting_table", CraftingTableBlock.CODEC);
        Registry.register(registry, "crop", CropBlock.CODEC);
        Registry.register(registry, "crying_obsidian", CryingObsidianBlock.CODEC);
        Registry.register(registry, "daylight_detector", DaylightDetectorBlock.CODEC);
        Registry.register(registry, "dry_vegetation", DryVegetationBlock.CODEC);
        Registry.register(registry, "decorated_pot", DecoratedPotBlock.CODEC);
        Registry.register(registry, "detector_rail", DetectorRailBlock.CODEC);
        Registry.register(registry, "dirt_path", DirtPathBlock.CODEC);
        Registry.register(registry, "dispenser", DispenserBlock.CODEC);
        Registry.register(registry, "door", DoorBlock.CODEC);
        Registry.register(registry, "double_plant", DoublePlantBlock.CODEC);
        Registry.register(registry, "dragon_egg", DragonEggBlock.CODEC);
        Registry.register(registry, "dried_ghast", DriedGhastBlock.CODEC);
        Registry.register(registry, "drop_experience", DropExperienceBlock.CODEC);
        Registry.register(registry, "dropper", DropperBlock.CODEC);
        Registry.register(registry, "enchantment_table", EnchantingTableBlock.CODEC);
        Registry.register(registry, "ender_chest", EnderChestBlock.CODEC);
        Registry.register(registry, "end_gateway", EndGatewayBlock.CODEC);
        Registry.register(registry, "end_portal", EndPortalBlock.CODEC);
        Registry.register(registry, "end_portal_frame", EndPortalFrameBlock.CODEC);
        Registry.register(registry, "end_rod", EndRodBlock.CODEC);
        Registry.register(registry, "eyeblossom", EyeblossomBlock.CODEC);
        Registry.register(registry, "farmland", FarmlandBlock.CODEC);
        Registry.register(registry, "bonemealable_feature_placer", BonemealableFeaturePlacerBlock.CODEC);
        Registry.register(registry, "fence", FenceBlock.CODEC);
        Registry.register(registry, "fence_gate", FenceGateBlock.CODEC);
        Registry.register(registry, "fire", FireBlock.CODEC);
        Registry.register(registry, "firefly_bush", FireflyBushBlock.CODEC);
        Registry.register(registry, "flower", FlowerBlock.CODEC);
        Registry.register(registry, "flower_pot", FlowerPotBlock.CODEC);
        Registry.register(registry, "frogspawn", FrogspawnBlock.CODEC);
        Registry.register(registry, "frosted_ice", FrostedIceBlock.CODEC);
        Registry.register(registry, "nether_fungus", NetherFungusBlock.CODEC);
        Registry.register(registry, "furnace", FurnaceBlock.CODEC);
        Registry.register(registry, "glazed_terracotta", GlazedTerracottaBlock.CODEC);
        Registry.register(registry, "glow_lichen", GlowLichenBlock.CODEC);
        Registry.register(registry, "grass", GrassBlock.CODEC);
        Registry.register(registry, "grindstone", GrindstoneBlock.CODEC);
        Registry.register(registry, "half_transparent", HalfTransparentBlock.CODEC);
        Registry.register(registry, "hanging_moss", HangingMossBlock.CODEC);
        Registry.register(registry, "hanging_roots", HangingRootsBlock.CODEC);
        Registry.register(registry, "hay", HayBlock.CODEC);
        Registry.register(registry, "heavy_core", HeavyCoreBlock.CODEC);
        Registry.register(registry, "honey", HoneyBlock.CODEC);
        Registry.register(registry, "hopper", HopperBlock.CODEC);
        Registry.register(registry, "huge_mushroom", HugeMushroomBlock.CODEC);
        Registry.register(registry, "ice", IceBlock.CODEC);
        Registry.register(registry, "infested", InfestedBlock.CODEC);
        Registry.register(registry, "infested_rotated_pillar", InfestedRotatedPillarBlock.CODEC);
        Registry.register(registry, "iron_bars", IronBarsBlock.CODEC);
        Registry.register(registry, "jack_o_lantern", CarvedPumpkinBlock.CODEC);
        Registry.register(registry, "jigsaw", JigsawBlock.CODEC);
        Registry.register(registry, "jukebox", JukeboxBlock.CODEC);
        Registry.register(registry, "kelp", KelpBlock.CODEC);
        Registry.register(registry, "kelp_plant", KelpPlantBlock.CODEC);
        Registry.register(registry, "ladder", LadderBlock.CODEC);
        Registry.register(registry, "lantern", LanternBlock.CODEC);
        Registry.register(registry, "lava_cauldron", LavaCauldronBlock.CODEC);
        Registry.register(registry, "layered_cauldron", LayeredCauldronBlock.CODEC);
        Registry.register(registry, "leaf_litter", LeafLitterBlock.CODEC);
        Registry.register(registry, "lectern", LecternBlock.CODEC);
        Registry.register(registry, "lever", LeverBlock.CODEC);
        Registry.register(registry, "light", LightBlock.CODEC);
        Registry.register(registry, "lightning_rod", LightningRodBlock.CODEC);
        Registry.register(registry, "liquid", LiquidBlock.CODEC);
        Registry.register(registry, "loom", LoomBlock.CODEC);
        Registry.register(registry, "magma", MagmaBlock.CODEC);
        Registry.register(registry, "mangrove_leaves", MangroveLeavesBlock.CODEC);
        Registry.register(registry, "mangrove_propagule", MangrovePropaguleBlock.CODEC);
        Registry.register(registry, "mangrove_roots", MangroveRootsBlock.CODEC);
        Registry.register(registry, "mossy_carpet", MossyCarpetBlock.CODEC);
        Registry.register(registry, "moving_piston", MovingPistonBlock.CODEC);
        Registry.register(registry, "mud", MudBlock.CODEC);
        Registry.register(registry, "multiface", MultifaceBlock.CODEC);
        Registry.register(registry, "mushroom", MushroomBlock.CODEC);
        Registry.register(registry, "mycelium", MyceliumBlock.CODEC);
        Registry.register(registry, "nether_portal", NetherPortalBlock.CODEC);
        Registry.register(registry, "netherrack", NetherrackBlock.CODEC);
        Registry.register(registry, "nether_sprouts", NetherSproutsBlock.CODEC);
        Registry.register(registry, "nether_wart", NetherWartBlock.CODEC);
        Registry.register(registry, "note", NoteBlock.CODEC);
        Registry.register(registry, "nylium", NyliumBlock.CODEC);
        Registry.register(registry, "observer", ObserverBlock.CODEC);
        Registry.register(registry, "piglinwallskull", PiglinWallSkullBlock.CODEC);
        Registry.register(registry, "flower_bed", FlowerBedBlock.CODEC);
        Registry.register(registry, "piston_base", PistonBaseBlock.CODEC);
        Registry.register(registry, "piston_head", PistonHeadBlock.CODEC);
        Registry.register(registry, "pitcher_crop", PitcherCropBlock.CODEC);
        Registry.register(registry, "player_head", PlayerHeadBlock.CODEC);
        Registry.register(registry, "player_wall_head", PlayerWallHeadBlock.CODEC);
        Registry.register(registry, "pointed_dripstone", PointedDripstoneBlock.CODEC);
        Registry.register(registry, "potato", PotatoBlock.CODEC);
        Registry.register(registry, "powder_snow", PowderSnowBlock.CODEC);
        Registry.register(registry, "powered", PoweredBlock.CODEC);
        Registry.register(registry, "powered_rail", PoweredRailBlock.CODEC);
        Registry.register(registry, "pressure_plate", PressurePlateBlock.CODEC);
        Registry.register(registry, "pumpkin", PumpkinBlock.CODEC);
        Registry.register(registry, "rail", RailBlock.CODEC);
        Registry.register(registry, "redstone_lamp", RedstoneLampBlock.CODEC);
        Registry.register(registry, "redstone_ore", RedStoneOreBlock.CODEC);
        Registry.register(registry, "redstone_torch", RedstoneTorchBlock.CODEC);
        Registry.register(registry, "redstone_wall_torch", RedstoneWallTorchBlock.CODEC);
        Registry.register(registry, "redstone_wire", RedStoneWireBlock.CODEC);
        Registry.register(registry, "repeater", RepeaterBlock.CODEC);
        Registry.register(registry, "respawn_anchor", RespawnAnchorBlock.CODEC);
        Registry.register(registry, "rooted_dirt", RootedDirtBlock.CODEC);
        Registry.register(registry, "nether_roots", NetherRootsBlock.CODEC);
        Registry.register(registry, "rotated_pillar", RotatedPillarBlock.CODEC);
        Registry.register(registry, "sapling", SaplingBlock.CODEC);
        Registry.register(registry, "sand", SandBlock.CODEC);
        Registry.register(registry, "scaffolding", ScaffoldingBlock.CODEC);
        Registry.register(registry, "sculk_catalyst", SculkCatalystBlock.CODEC);
        Registry.register(registry, "sculk", SculkBlock.CODEC);
        Registry.register(registry, "sculk_sensor", SculkSensorBlock.CODEC);
        Registry.register(registry, "sculk_shrieker", SculkShriekerBlock.CODEC);
        Registry.register(registry, "sculk_vein", SculkVeinBlock.CODEC);
        Registry.register(registry, "seagrass", SeagrassBlock.CODEC);
        Registry.register(registry, "sea_pickle", SeaPickleBlock.CODEC);
        Registry.register(registry, "shelf", ShelfBlock.CODEC);
        Registry.register(registry, "short_dry_grass", ShortDryGrassBlock.CODEC);
        Registry.register(registry, "shulker_box", ShulkerBoxBlock.CODEC);
        Registry.register(registry, "skull", SkullBlock.CODEC);
        Registry.register(registry, "slab", SlabBlock.CODEC);
        Registry.register(registry, "slime", SlimeBlock.CODEC);
        Registry.register(registry, "small_dripleaf", SmallDripleafBlock.CODEC);
        Registry.register(registry, "smithing_table", SmithingTableBlock.CODEC);
        Registry.register(registry, "smoker", SmokerBlock.CODEC);
        Registry.register(registry, "sniffer_egg", SnifferEggBlock.CODEC);
        Registry.register(registry, "snow_layer", SnowLayerBlock.CODEC);
        Registry.register(registry, "snowy_dirt", SnowyBlock.CODEC);
        Registry.register(registry, "soul_fire", SoulFireBlock.CODEC);
        Registry.register(registry, "soul_sand", SoulSandBlock.CODEC);
        Registry.register(registry, "spawner", SpawnerBlock.CODEC);
        Registry.register(registry, "creaking_heart", CreakingHeartBlock.CODEC);
        Registry.register(registry, "sponge", SpongeBlock.CODEC);
        Registry.register(registry, "spore_blossom", SporeBlossomBlock.CODEC);
        Registry.register(registry, "stained_glass_pane", StainedGlassPaneBlock.CODEC);
        Registry.register(registry, "stained_glass", StainedGlassBlock.CODEC);
        Registry.register(registry, "stair", StairBlock.CODEC);
        Registry.register(registry, "standing_sign", StandingSignBlock.CODEC);
        Registry.register(registry, "stem", StemBlock.CODEC);
        Registry.register(registry, "stonecutter", StonecutterBlock.CODEC);
        Registry.register(registry, "structure", StructureBlock.CODEC);
        Registry.register(registry, "structure_void", StructureVoidBlock.CODEC);
        Registry.register(registry, "sugar_cane", SugarCaneBlock.CODEC);
        Registry.register(registry, "sweet_berry_bush", SweetBerryBushBlock.CODEC);
        Registry.register(registry, "tall_dry_grass", TallDryGrassBlock.CODEC);
        Registry.register(registry, "tall_flower", TallFlowerBlock.CODEC);
        Registry.register(registry, "tall_grass", TallGrassBlock.CODEC);
        Registry.register(registry, "tall_seagrass", TallSeagrassBlock.CODEC);
        Registry.register(registry, "target", TargetBlock.CODEC);
        Registry.register(registry, "test", TestBlock.CODEC);
        Registry.register(registry, "test_instance", TestInstanceBlock.CODEC);
        Registry.register(registry, "tinted_glass", TintedGlassBlock.CODEC);
        Registry.register(registry, "tinted_particle_leaves", TintedParticleLeavesBlock.CODEC);
        Registry.register(registry, "tnt", TntBlock.CODEC);
        Registry.register(registry, "torchflower_crop", TorchflowerCropBlock.CODEC);
        Registry.register(registry, "torch", TorchBlock.CODEC);
        Registry.register(registry, "transparent", TransparentBlock.CODEC);
        Registry.register(registry, "trapdoor", TrapDoorBlock.CODEC);
        Registry.register(registry, "trapped_chest", TrappedChestBlock.CODEC);
        Registry.register(registry, "trial_spawner", TrialSpawnerBlock.CODEC);
        Registry.register(registry, "trip_wire_hook", TripWireHookBlock.CODEC);
        Registry.register(registry, "tripwire", TripWireBlock.CODEC);
        Registry.register(registry, "turtle_egg", TurtleEggBlock.CODEC);
        Registry.register(registry, "twisting_vines_plant", TwistingVinesPlantBlock.CODEC);
        Registry.register(registry, "twisting_vines", TwistingVinesBlock.CODEC);
        Registry.register(registry, "untinted_particle_leaves", UntintedParticleLeavesBlock.CODEC);
        Registry.register(registry, "vault", VaultBlock.CODEC);
        Registry.register(registry, "vine", VineBlock.CODEC);
        Registry.register(registry, "wall_banner", WallBannerBlock.CODEC);
        Registry.register(registry, "wall_hanging_sign", WallHangingSignBlock.CODEC);
        Registry.register(registry, "wall_sign", WallSignBlock.CODEC);
        Registry.register(registry, "wall_skull", WallSkullBlock.CODEC);
        Registry.register(registry, "wall_torch", WallTorchBlock.CODEC);
        Registry.register(registry, "wall", WallBlock.CODEC);
        Registry.register(registry, "lily_pad", LilyPadBlock.CODEC);
        Registry.register(registry, "waterlogged_transparent", WaterloggedTransparentBlock.CODEC);
        Registry.register(registry, "weathering_copper_bar", WeatheringCopperBarsBlock.CODEC);
        Registry.register(registry, "weathering_copper_bulb", WeatheringCopperBulbBlock.CODEC);
        Registry.register(registry, "weathering_copper_chain", WeatheringCopperChainBlock.CODEC);
        Registry.register(registry, "weathering_copper_chest", WeatheringCopperChestBlock.CODEC);
        Registry.register(registry, "weathering_copper_door", WeatheringCopperDoorBlock.CODEC);
        Registry.register(registry, "weathering_copper_full", WeatheringCopperFullBlock.CODEC);
        Registry.register(registry, "weathering_copper_golem_statue", WeatheringCopperGolemStatueBlock.CODEC);
        Registry.register(registry, "weathering_copper_grate", WeatheringCopperGrateBlock.CODEC);
        Registry.register(registry, "weathering_copper_slab", WeatheringCopperSlabBlock.CODEC);
        Registry.register(registry, "weathering_copper_stair", WeatheringCopperStairBlock.CODEC);
        Registry.register(registry, "weathering_copper_trap_door", WeatheringCopperTrapDoorBlock.CODEC);
        Registry.register(registry, "weathering_lantern", WeatheringLanternBlock.CODEC);
        Registry.register(registry, "weathering_lightning_rod", WeatheringLightningRodBlock.CODEC);
        Registry.register(registry, "web", WebBlock.CODEC);
        Registry.register(registry, "weeping_vines_plant", WeepingVinesPlantBlock.CODEC);
        Registry.register(registry, "weeping_vines", WeepingVinesBlock.CODEC);
        Registry.register(registry, "weighted_pressure_plate", WeightedPressurePlateBlock.CODEC);
        Registry.register(registry, "wet_sponge", WetSpongeBlock.CODEC);
        Registry.register(registry, "wither_rose", WitherRoseBlock.CODEC);
        Registry.register(registry, "wither_skull", WitherSkullBlock.CODEC);
        Registry.register(registry, "wither_wall_skull", WitherWallSkullBlock.CODEC);
        return Registry.register(registry, "wool_carpet", WoolCarpetBlock.CODEC);
    }
}

