/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableMap
 *  com.google.common.collect.ImmutableMap$Builder
 */
package net.minecraft.client.model.geom;

import com.google.common.collect.ImmutableMap;
import java.util.List;
import java.util.Map;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.ambient.BatModel;
import net.minecraft.client.model.animal.allay.AllayModel;
import net.minecraft.client.model.animal.armadillo.AdultArmadilloModel;
import net.minecraft.client.model.animal.armadillo.BabyArmadilloModel;
import net.minecraft.client.model.animal.axolotl.AdultAxolotlModel;
import net.minecraft.client.model.animal.axolotl.BabyAxolotlModel;
import net.minecraft.client.model.animal.bee.AdultBeeModel;
import net.minecraft.client.model.animal.bee.BabyBeeModel;
import net.minecraft.client.model.animal.bee.BeeStingerModel;
import net.minecraft.client.model.animal.camel.AdultCamelModel;
import net.minecraft.client.model.animal.camel.BabyCamelModel;
import net.minecraft.client.model.animal.camel.CamelSaddleModel;
import net.minecraft.client.model.animal.chicken.AdultChickenModel;
import net.minecraft.client.model.animal.chicken.BabyChickenModel;
import net.minecraft.client.model.animal.chicken.ColdChickenModel;
import net.minecraft.client.model.animal.cow.BabyCowModel;
import net.minecraft.client.model.animal.cow.ColdCowModel;
import net.minecraft.client.model.animal.cow.CowModel;
import net.minecraft.client.model.animal.cow.WarmCowModel;
import net.minecraft.client.model.animal.dolphin.BabyDolphinModel;
import net.minecraft.client.model.animal.dolphin.DolphinModel;
import net.minecraft.client.model.animal.equine.AbstractEquineModel;
import net.minecraft.client.model.animal.equine.BabyDonkeyModel;
import net.minecraft.client.model.animal.equine.BabyHorseModel;
import net.minecraft.client.model.animal.equine.DonkeyModel;
import net.minecraft.client.model.animal.equine.EquineSaddleModel;
import net.minecraft.client.model.animal.feline.AdultCatModel;
import net.minecraft.client.model.animal.feline.AdultFelineModel;
import net.minecraft.client.model.animal.feline.BabyCatModel;
import net.minecraft.client.model.animal.feline.BabyFelineModel;
import net.minecraft.client.model.animal.fish.CodModel;
import net.minecraft.client.model.animal.fish.PufferfishBigModel;
import net.minecraft.client.model.animal.fish.PufferfishMidModel;
import net.minecraft.client.model.animal.fish.PufferfishSmallModel;
import net.minecraft.client.model.animal.fish.SalmonModel;
import net.minecraft.client.model.animal.fish.TropicalFishLargeModel;
import net.minecraft.client.model.animal.fish.TropicalFishSmallModel;
import net.minecraft.client.model.animal.fox.AdultFoxModel;
import net.minecraft.client.model.animal.fox.BabyFoxModel;
import net.minecraft.client.model.animal.frog.FrogModel;
import net.minecraft.client.model.animal.frog.TadpoleModel;
import net.minecraft.client.model.animal.ghast.HappyGhastHarnessModel;
import net.minecraft.client.model.animal.ghast.HappyGhastModel;
import net.minecraft.client.model.animal.goat.BabyGoatModel;
import net.minecraft.client.model.animal.goat.GoatModel;
import net.minecraft.client.model.animal.golem.CopperGolemModel;
import net.minecraft.client.model.animal.golem.IronGolemModel;
import net.minecraft.client.model.animal.golem.SnowGolemModel;
import net.minecraft.client.model.animal.llama.BabyLlamaModel;
import net.minecraft.client.model.animal.llama.LlamaModel;
import net.minecraft.client.model.animal.llama.LlamaSpitModel;
import net.minecraft.client.model.animal.nautilus.NautilusArmorModel;
import net.minecraft.client.model.animal.nautilus.NautilusModel;
import net.minecraft.client.model.animal.nautilus.NautilusSaddleModel;
import net.minecraft.client.model.animal.panda.BabyPandaModel;
import net.minecraft.client.model.animal.panda.PandaModel;
import net.minecraft.client.model.animal.parrot.ParrotModel;
import net.minecraft.client.model.animal.pig.BabyPigModel;
import net.minecraft.client.model.animal.pig.ColdPigModel;
import net.minecraft.client.model.animal.pig.PigModel;
import net.minecraft.client.model.animal.polarbear.BabyPolarBearModel;
import net.minecraft.client.model.animal.polarbear.PolarBearModel;
import net.minecraft.client.model.animal.rabbit.AdultRabbitModel;
import net.minecraft.client.model.animal.rabbit.BabyRabbitModel;
import net.minecraft.client.model.animal.sheep.BabySheepModel;
import net.minecraft.client.model.animal.sheep.SheepFurModel;
import net.minecraft.client.model.animal.sheep.SheepModel;
import net.minecraft.client.model.animal.sniffer.SnifferModel;
import net.minecraft.client.model.animal.sniffer.SniffletModel;
import net.minecraft.client.model.animal.squid.BabySquidModel;
import net.minecraft.client.model.animal.squid.SquidModel;
import net.minecraft.client.model.animal.turtle.AdultTurtleModel;
import net.minecraft.client.model.animal.turtle.BabyTurtleModel;
import net.minecraft.client.model.animal.wolf.AdultWolfModel;
import net.minecraft.client.model.animal.wolf.BabyWolfModel;
import net.minecraft.client.model.effects.EvokerFangsModel;
import net.minecraft.client.model.effects.SpinAttackEffectModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelLayers;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshTransformer;
import net.minecraft.client.model.monster.blaze.BlazeModel;
import net.minecraft.client.model.monster.breeze.BreezeModel;
import net.minecraft.client.model.monster.creaking.CreakingModel;
import net.minecraft.client.model.monster.creeper.CreeperModel;
import net.minecraft.client.model.monster.dragon.EnderDragonModel;
import net.minecraft.client.model.monster.enderman.EndermanModel;
import net.minecraft.client.model.monster.endermite.EndermiteModel;
import net.minecraft.client.model.monster.ghast.GhastModel;
import net.minecraft.client.model.monster.guardian.GuardianModel;
import net.minecraft.client.model.monster.hoglin.BabyHoglinModel;
import net.minecraft.client.model.monster.hoglin.HoglinModel;
import net.minecraft.client.model.monster.illager.IllagerModel;
import net.minecraft.client.model.monster.nautilus.ZombieNautilusCoralModel;
import net.minecraft.client.model.monster.phantom.PhantomModel;
import net.minecraft.client.model.monster.piglin.AbstractPiglinModel;
import net.minecraft.client.model.monster.piglin.AdultPiglinModel;
import net.minecraft.client.model.monster.piglin.AdultZombifiedPiglinModel;
import net.minecraft.client.model.monster.piglin.BabyPiglinModel;
import net.minecraft.client.model.monster.piglin.BabyZombifiedPiglinModel;
import net.minecraft.client.model.monster.piglin.PiglinModel;
import net.minecraft.client.model.monster.ravager.RavagerModel;
import net.minecraft.client.model.monster.shulker.ShulkerModel;
import net.minecraft.client.model.monster.silverfish.SilverfishModel;
import net.minecraft.client.model.monster.skeleton.BoggedModel;
import net.minecraft.client.model.monster.skeleton.SkeletonModel;
import net.minecraft.client.model.monster.slime.MagmaCubeModel;
import net.minecraft.client.model.monster.slime.SlimeModel;
import net.minecraft.client.model.monster.spider.SpiderModel;
import net.minecraft.client.model.monster.strider.AdultStriderModel;
import net.minecraft.client.model.monster.strider.BabyStriderModel;
import net.minecraft.client.model.monster.vex.VexModel;
import net.minecraft.client.model.monster.warden.WardenModel;
import net.minecraft.client.model.monster.witch.WitchModel;
import net.minecraft.client.model.monster.wither.WitherBossModel;
import net.minecraft.client.model.monster.zombie.BabyDrownedModel;
import net.minecraft.client.model.monster.zombie.BabyZombieModel;
import net.minecraft.client.model.monster.zombie.BabyZombieVillagerModel;
import net.minecraft.client.model.monster.zombie.DrownedModel;
import net.minecraft.client.model.monster.zombie.ZombieVillagerModel;
import net.minecraft.client.model.npc.BabyVillagerModel;
import net.minecraft.client.model.npc.VillagerModel;
import net.minecraft.client.model.object.armorstand.ArmorStandArmorModel;
import net.minecraft.client.model.object.armorstand.ArmorStandModel;
import net.minecraft.client.model.object.banner.BannerFlagModel;
import net.minecraft.client.model.object.banner.BannerModel;
import net.minecraft.client.model.object.bell.BellModel;
import net.minecraft.client.model.object.boat.BoatModel;
import net.minecraft.client.model.object.boat.RaftModel;
import net.minecraft.client.model.object.book.BookModel;
import net.minecraft.client.model.object.cart.MinecartModel;
import net.minecraft.client.model.object.chest.ChestModel;
import net.minecraft.client.model.object.crystal.EndCrystalModel;
import net.minecraft.client.model.object.equipment.ElytraModel;
import net.minecraft.client.model.object.equipment.ShieldModel;
import net.minecraft.client.model.object.leash.LeashKnotModel;
import net.minecraft.client.model.object.projectile.ArrowModel;
import net.minecraft.client.model.object.projectile.ShulkerBulletModel;
import net.minecraft.client.model.object.projectile.TridentModel;
import net.minecraft.client.model.object.projectile.WindChargeModel;
import net.minecraft.client.model.object.skull.DragonHeadModel;
import net.minecraft.client.model.object.skull.PiglinHeadModel;
import net.minecraft.client.model.object.skull.SkullModel;
import net.minecraft.client.model.player.PlayerCapeModel;
import net.minecraft.client.model.player.PlayerEarsModel;
import net.minecraft.client.model.player.PlayerModel;
import net.minecraft.client.renderer.blockentity.BedRenderer;
import net.minecraft.client.renderer.blockentity.ConduitRenderer;
import net.minecraft.client.renderer.blockentity.DecoratedPotRenderer;
import net.minecraft.client.renderer.blockentity.HangingSignRenderer;
import net.minecraft.client.renderer.blockentity.StandingSignRenderer;
import net.minecraft.client.renderer.entity.ArmorModelSet;
import net.minecraft.client.renderer.entity.WitherSkullRenderer;
import net.minecraft.world.level.block.HangingSignBlock;
import net.minecraft.world.level.block.state.properties.WoodType;

public class LayerDefinitions {
    private static final CubeDeformation FISH_PATTERN_DEFORMATION = new CubeDeformation(0.008f);
    private static final CubeDeformation OUTER_ARMOR_DEFORMATION = new CubeDeformation(1.0f);
    private static final CubeDeformation INNER_ARMOR_DEFORMATION = new CubeDeformation(0.5f);
    private static final CubeDeformation BABY_OUTER_ARMOR_DEFORMATION = new CubeDeformation(-0.1f, 0.5f, 0.3f);
    private static final CubeDeformation BABY_INNER_ARMOR_DEFORMATION = new CubeDeformation(-0.1f, 0.3f, 0.3f);
    private static final CubeDeformation BABY_PIGLIN_INNER_ARMOR_DEFORMATION = new CubeDeformation(0.7f);
    private static final CubeDeformation BABY_PIGLIN_OUTER_ARMOR_DEFORMATION = new CubeDeformation(0.7f);
    private static final PartPose BABY_PIGLIN_ARMOR_ARM_OFFSET = new PartPose(0.5f, -0.5f, -1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f);

    public static Map<ModelLayerLocation, LayerDefinition> createRoots() {
        ImmutableMap.Builder result = ImmutableMap.builder();
        LayerDefinition humanoidBodyLayer = LayerDefinition.create(HumanoidModel.createMesh(CubeDeformation.NONE, 0.0f), 64, 64);
        ArmorModelSet<LayerDefinition> humanoidArmor = HumanoidModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION).map(mesh -> LayerDefinition.create(mesh, 64, 32));
        ArmorModelSet<LayerDefinition> humanoidBabyArmor = HumanoidModel.createBabyArmorMeshSet(BABY_INNER_ARMOR_DEFORMATION, BABY_OUTER_ARMOR_DEFORMATION, PartPose.ZERO).map(mesh -> LayerDefinition.create(mesh, 64, 64));
        ArmorModelSet<LayerDefinition> playerArmor = PlayerModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION).map(mesh -> LayerDefinition.create(mesh, 64, 32));
        ArmorModelSet<LayerDefinition> piglinArmor = PiglinModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, new CubeDeformation(1.02f)).map(mesh -> LayerDefinition.create(mesh, 64, 32));
        ArmorModelSet<LayerDefinition> piglinBabyArmor = AbstractPiglinModel.createBabyArmorMeshSet(BABY_PIGLIN_INNER_ARMOR_DEFORMATION, BABY_PIGLIN_OUTER_ARMOR_DEFORMATION, BABY_PIGLIN_ARMOR_ARM_OFFSET).map(mesh -> LayerDefinition.create(mesh, 64, 64));
        LayerDefinition minecartBodyLayer = MinecartModel.createBodyLayer();
        LayerDefinition mobHeadLayer = SkullModel.createMobHeadLayer();
        LayerDefinition horseBodyLayer = LayerDefinition.create(AbstractEquineModel.createBodyMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition horseBabyLayer = LayerDefinition.create(BabyHorseModel.createBabyMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition horseSaddleLayer = EquineSaddleModel.createSaddleLayer();
        MeshTransformer villagerLikeScale = MeshTransformer.scaling(0.9375f);
        LayerDefinition illagerBodyLayer = IllagerModel.createBodyLayer().apply(villagerLikeScale);
        LayerDefinition axolotlBodyLayer = AdultAxolotlModel.createBodyLayer();
        LayerDefinition cowBodyLayer = CowModel.createBodyLayer();
        LayerDefinition coldChickenBodyLayer = ColdChickenModel.createBodyLayer();
        LayerDefinition coldCowBodyLayer = ColdCowModel.createBodyLayer();
        LayerDefinition coldPigBodyLayer = ColdPigModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition elytraLayer = ElytraModel.createLayer();
        LayerDefinition felineBodyLayer = LayerDefinition.create(AdultFelineModel.createBodyMesh(CubeDeformation.NONE), 64, 32);
        LayerDefinition felineBabyBodyLayer = BabyFelineModel.createBabyLayer();
        LayerDefinition felineCollarLayer = LayerDefinition.create(AdultFelineModel.createBodyMesh(AdultCatModel.COLLAR_DEFORMATION), 64, 32);
        LayerDefinition piglinLayer = AdultPiglinModel.createBodyLayer();
        LayerDefinition piglinHeadLayer = LayerDefinition.create(PiglinHeadModel.createHeadModel(), 64, 64);
        LayerDefinition humanoidHeadLayer = SkullModel.createHumanoidHeadLayer();
        LayerDefinition llamaBodyLayer = LlamaModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition llamaDecorLayer = LlamaModel.createBodyLayer(new CubeDeformation(0.5f));
        LayerDefinition llamaBabyBodyLayer = BabyLlamaModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition llamaBabyDecorLayer = BabyLlamaModel.createBodyLayer(new CubeDeformation(0.2f));
        LayerDefinition striderLayer = AdultStriderModel.createBodyLayer();
        LayerDefinition striderBabyLayer = BabyStriderModel.createBodyLayer();
        LayerDefinition hoglinLayer = HoglinModel.createBodyLayer();
        LayerDefinition hoglinBabyLayer = BabyHoglinModel.createBodyLayer();
        LayerDefinition skeletonBodyLayer = SkeletonModel.createBodyLayer();
        LayerDefinition villagerBodyLayer = LayerDefinition.create(VillagerModel.createBodyModel(), 64, 64).apply(villagerLikeScale);
        LayerDefinition villagerBabyLayer = LayerDefinition.create(BabyVillagerModel.createBodyModel(), 64, 64);
        LayerDefinition villagerNoHatLayer = LayerDefinition.create(VillagerModel.createNoHatModel(), 64, 64).apply(villagerLikeScale);
        LayerDefinition villagerBabyNoHatLayer = LayerDefinition.create(BabyVillagerModel.createNoHatModel(), 64, 64);
        LayerDefinition spiderBodyLayer = SpiderModel.createSpiderBodyLayer();
        LayerDefinition camelBodyLayer = AdultCamelModel.createBodyLayer();
        LayerDefinition camelBabyBodyLayer = BabyCamelModel.createBodyLayer();
        LayerDefinition camelSaddleLayer = CamelSaddleModel.createSaddleLayer();
        LayerDefinition chickenBodyLayer = AdultChickenModel.createBodyLayer();
        LayerDefinition pandaBodyLayer = PandaModel.createBodyLayer();
        LayerDefinition pandaBabyBodyLayer = BabyPandaModel.createBodyLayer();
        LayerDefinition pigBodyLayer = PigModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition pigSaddleLayer = PigModel.createBodyLayer(new CubeDeformation(0.5f));
        LayerDefinition sheepBodyLayer = SheepModel.createBodyLayer();
        LayerDefinition sheepBabyBodyLayer = BabySheepModel.createBodyLayer();
        LayerDefinition sheepWoolLayer = SheepFurModel.createFurLayer();
        LayerDefinition snifferBodyLayer = SnifferModel.createBodyLayer();
        LayerDefinition snifferBabyBodyLayer = SniffletModel.createBodyLayer();
        LayerDefinition turtleBodyLayer = AdultTurtleModel.createBodyLayer();
        LayerDefinition warmCowBodyLayer = WarmCowModel.createBodyLayer();
        LayerDefinition wolfBodyLayer = LayerDefinition.create(AdultWolfModel.createBodyLayer(CubeDeformation.NONE), 64, 32);
        LayerDefinition wolfArmorLayer = LayerDefinition.create(AdultWolfModel.createBodyLayer(new CubeDeformation(0.2f)), 64, 32);
        LayerDefinition zombieVillagerBodyLayer = ZombieVillagerModel.createBodyLayer();
        LayerDefinition babyZombieVillagerBodyLayer = BabyZombieVillagerModel.createBodyLayer();
        LayerDefinition zombieVillagerNoHatLayer = ZombieVillagerModel.createNoHatLayer();
        LayerDefinition babyZombieVillagerNoHatLayer = BabyZombieVillagerModel.createNoHatLayer();
        LayerDefinition armorStandBodyLayer = ArmorStandModel.createBodyLayer();
        ArmorModelSet<LayerDefinition> armorStandArmor = ArmorStandArmorModel.createArmorLayerSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION);
        LayerDefinition drownedBodyLayer = DrownedModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition babyDrownedBodyLayer = BabyDrownedModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition drownedOuterLayer = DrownedModel.createBodyLayer(new CubeDeformation(0.25f));
        LayerDefinition babyDrownedOuterLayer = BabyDrownedModel.createBodyLayer(new CubeDeformation(0.25f));
        LayerDefinition squidBodyLayer = SquidModel.createBodyLayer();
        LayerDefinition squidBabyBodyLayer = BabySquidModel.createBodyLayer();
        LayerDefinition dolphinBodyLayer = DolphinModel.createBodyLayer();
        LayerDefinition dolphinBabyBodyLayer = BabyDolphinModel.createBodyLayer();
        LayerDefinition salmonBodyLayer = SalmonModel.createBodyLayer();
        LayerDefinition nautilusSaddleLayer = NautilusSaddleModel.createSaddleLayer();
        LayerDefinition babyZombieLayer = BabyZombieModel.createBodyLayer(CubeDeformation.NONE);
        result.put((Object)ModelLayers.ALLAY, (Object)AllayModel.createBodyLayer());
        result.put((Object)ModelLayers.ARMADILLO, (Object)AdultArmadilloModel.createBodyLayer());
        result.put((Object)ModelLayers.ARMADILLO_BABY, (Object)BabyArmadilloModel.createBodyLayer());
        result.put((Object)ModelLayers.ARMOR_STAND, (Object)armorStandBodyLayer);
        ModelLayers.ARMOR_STAND_ARMOR.putFrom(armorStandArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.ARMOR_STAND_SMALL, (Object)armorStandBodyLayer.apply(HumanoidModel.BABY_TRANSFORMER));
        ModelLayers.ARMOR_STAND_SMALL_ARMOR.putFrom(armorStandArmor.map(layer -> layer.apply(HumanoidModel.BABY_TRANSFORMER)), (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.ARROW, (Object)ArrowModel.createBodyLayer());
        result.put((Object)ModelLayers.AXOLOTL, (Object)axolotlBodyLayer);
        result.put((Object)ModelLayers.AXOLOTL_BABY, (Object)BabyAxolotlModel.createBodyLayer());
        result.put((Object)ModelLayers.STANDING_BANNER, (Object)BannerModel.createBodyLayer(true));
        result.put((Object)ModelLayers.WALL_BANNER, (Object)BannerModel.createBodyLayer(false));
        result.put((Object)ModelLayers.STANDING_BANNER_FLAG, (Object)BannerFlagModel.createFlagLayer(true));
        result.put((Object)ModelLayers.WALL_BANNER_FLAG, (Object)BannerFlagModel.createFlagLayer(false));
        result.put((Object)ModelLayers.BAT, (Object)BatModel.createBodyLayer());
        result.put((Object)ModelLayers.BED_FOOT, (Object)BedRenderer.createFootLayer());
        result.put((Object)ModelLayers.BED_HEAD, (Object)BedRenderer.createHeadLayer());
        result.put((Object)ModelLayers.BEE, (Object)AdultBeeModel.createBodyLayer());
        result.put((Object)ModelLayers.BEE_BABY, (Object)BabyBeeModel.createBodyLayer());
        result.put((Object)ModelLayers.BEE_STINGER, (Object)BeeStingerModel.createBodyLayer());
        result.put((Object)ModelLayers.BELL, (Object)BellModel.createBodyLayer());
        result.put((Object)ModelLayers.BLAZE, (Object)BlazeModel.createBodyLayer());
        result.put((Object)ModelLayers.BOAT_WATER_PATCH, (Object)BoatModel.createWaterPatch());
        result.put((Object)ModelLayers.BOGGED, (Object)BoggedModel.createBodyLayer());
        ModelLayers.BOGGED_ARMOR.putFrom(humanoidArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.BOGGED_OUTER_LAYER, (Object)LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.2f), 0.0f), 64, 32));
        result.put((Object)ModelLayers.BOOK, (Object)BookModel.createBodyLayer());
        result.put((Object)ModelLayers.BREEZE, (Object)BreezeModel.createBodyLayer());
        result.put((Object)ModelLayers.BREEZE_WIND, (Object)BreezeModel.createWindLayer());
        result.put((Object)ModelLayers.BREEZE_EYES, (Object)BreezeModel.createEyesLayer());
        result.put((Object)ModelLayers.CAT, (Object)felineBodyLayer.apply(AdultCatModel.CAT_TRANSFORMER));
        result.put((Object)ModelLayers.CAT_BABY, (Object)felineBabyBodyLayer.apply(AdultCatModel.CAT_TRANSFORMER));
        result.put((Object)ModelLayers.CAT_COLLAR, (Object)felineCollarLayer.apply(AdultCatModel.CAT_TRANSFORMER));
        result.put((Object)ModelLayers.CAT_BABY_COLLAR, (Object)felineBabyBodyLayer.apply(AdultCatModel.CAT_TRANSFORMER).apply(BabyCatModel.COLLAR_TRANSFORMER));
        result.put((Object)ModelLayers.CAMEL, (Object)camelBodyLayer);
        result.put((Object)ModelLayers.CAMEL_BABY, (Object)camelBabyBodyLayer);
        result.put((Object)ModelLayers.CAMEL_SADDLE, (Object)camelSaddleLayer);
        result.put((Object)ModelLayers.CAMEL_HUSK_SADDLE, (Object)camelSaddleLayer);
        result.put((Object)ModelLayers.CAVE_SPIDER, (Object)spiderBodyLayer.apply(MeshTransformer.scaling(0.7f)));
        result.put((Object)ModelLayers.CHEST, (Object)ChestModel.createSingleBodyLayer());
        result.put((Object)ModelLayers.CHEST_MINECART, (Object)minecartBodyLayer);
        result.put((Object)ModelLayers.CHICKEN, (Object)chickenBodyLayer);
        result.put((Object)ModelLayers.CHICKEN_BABY, (Object)BabyChickenModel.createBodyLayer());
        result.put((Object)ModelLayers.COD, (Object)CodModel.createBodyLayer());
        result.put((Object)ModelLayers.COLD_CHICKEN, (Object)coldChickenBodyLayer);
        result.put((Object)ModelLayers.COLD_COW, (Object)coldCowBodyLayer);
        result.put((Object)ModelLayers.COLD_COW_BABY, (Object)BabyCowModel.createBodyLayer());
        result.put((Object)ModelLayers.COLD_PIG, (Object)coldPigBodyLayer);
        result.put((Object)ModelLayers.COMMAND_BLOCK_MINECART, (Object)minecartBodyLayer);
        result.put((Object)ModelLayers.CONDUIT_EYE, (Object)ConduitRenderer.createEyeLayer());
        result.put((Object)ModelLayers.CONDUIT_WIND, (Object)ConduitRenderer.createWindLayer());
        result.put((Object)ModelLayers.CONDUIT_SHELL, (Object)ConduitRenderer.createShellLayer());
        result.put((Object)ModelLayers.CONDUIT_CAGE, (Object)ConduitRenderer.createCageLayer());
        result.put((Object)ModelLayers.COPPER_GOLEM, (Object)CopperGolemModel.createBodyLayer());
        result.put((Object)ModelLayers.COPPER_GOLEM_EYES, (Object)CopperGolemModel.createEyesLayer());
        result.put((Object)ModelLayers.COPPER_GOLEM_RUNNING, (Object)CopperGolemModel.createRunningPoseBodyLayer());
        result.put((Object)ModelLayers.COPPER_GOLEM_SITTING, (Object)CopperGolemModel.createSittingPoseBodyLayer());
        result.put((Object)ModelLayers.COPPER_GOLEM_STAR, (Object)CopperGolemModel.createStarPoseBodyLayer());
        result.put((Object)ModelLayers.COW, (Object)cowBodyLayer);
        result.put((Object)ModelLayers.COW_BABY, (Object)BabyCowModel.createBodyLayer());
        result.put((Object)ModelLayers.CREAKING, (Object)CreakingModel.createBodyLayer());
        result.put((Object)ModelLayers.CREAKING_EYES, (Object)CreakingModel.createEyesLayer());
        result.put((Object)ModelLayers.CREEPER, (Object)CreeperModel.createBodyLayer(CubeDeformation.NONE));
        result.put((Object)ModelLayers.CREEPER_ARMOR, (Object)CreeperModel.createBodyLayer(new CubeDeformation(2.0f)));
        result.put((Object)ModelLayers.CREEPER_HEAD, (Object)mobHeadLayer);
        result.put((Object)ModelLayers.DECORATED_POT_BASE, (Object)DecoratedPotRenderer.createBaseLayer());
        result.put((Object)ModelLayers.DECORATED_POT_SIDES, (Object)DecoratedPotRenderer.createSidesLayer());
        result.put((Object)ModelLayers.DOLPHIN, (Object)dolphinBodyLayer);
        result.put((Object)ModelLayers.DOLPHIN_BABY, (Object)dolphinBabyBodyLayer);
        result.put((Object)ModelLayers.DONKEY, (Object)DonkeyModel.createBodyLayer(0.87f));
        result.put((Object)ModelLayers.DONKEY_BABY, (Object)BabyDonkeyModel.createBabyLayer());
        result.put((Object)ModelLayers.DONKEY_SADDLE, (Object)DonkeyModel.createSaddleLayer(0.87f));
        result.put((Object)ModelLayers.DOUBLE_CHEST_LEFT, (Object)ChestModel.createDoubleBodyLeftLayer());
        result.put((Object)ModelLayers.DOUBLE_CHEST_RIGHT, (Object)ChestModel.createDoubleBodyRightLayer());
        result.put((Object)ModelLayers.DRAGON_SKULL, (Object)DragonHeadModel.createHeadLayer());
        result.put((Object)ModelLayers.DROWNED, (Object)drownedBodyLayer);
        ModelLayers.DROWNED_ARMOR.putFrom(humanoidArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.DROWNED_OUTER_LAYER, (Object)drownedOuterLayer);
        result.put((Object)ModelLayers.DROWNED_BABY, (Object)babyDrownedBodyLayer);
        ModelLayers.DROWNED_BABY_ARMOR.putFrom(humanoidBabyArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.DROWNED_BABY_OUTER_LAYER, (Object)babyDrownedOuterLayer);
        result.put((Object)ModelLayers.ELDER_GUARDIAN, (Object)GuardianModel.createElderGuardianLayer());
        result.put((Object)ModelLayers.ELYTRA, (Object)elytraLayer);
        result.put((Object)ModelLayers.ELYTRA_BABY, (Object)elytraLayer.apply(ElytraModel.BABY_TRANSFORMER));
        result.put((Object)ModelLayers.ENDERMAN, (Object)EndermanModel.createBodyLayer());
        result.put((Object)ModelLayers.ENDERMITE, (Object)EndermiteModel.createBodyLayer());
        result.put((Object)ModelLayers.ENDER_DRAGON, (Object)EnderDragonModel.createBodyLayer());
        result.put((Object)ModelLayers.END_CRYSTAL, (Object)EndCrystalModel.createBodyLayer());
        result.put((Object)ModelLayers.EVOKER, (Object)illagerBodyLayer);
        result.put((Object)ModelLayers.EVOKER_FANGS, (Object)EvokerFangsModel.createBodyLayer());
        result.put((Object)ModelLayers.FOX, (Object)AdultFoxModel.createBodyLayer());
        result.put((Object)ModelLayers.FOX_BABY, (Object)BabyFoxModel.createBodyLayer());
        result.put((Object)ModelLayers.FROG, (Object)FrogModel.createBodyLayer());
        result.put((Object)ModelLayers.FURNACE_MINECART, (Object)minecartBodyLayer);
        result.put((Object)ModelLayers.GHAST, (Object)GhastModel.createBodyLayer());
        MeshTransformer giantScale = MeshTransformer.scaling(6.0f);
        result.put((Object)ModelLayers.GIANT, (Object)humanoidBodyLayer.apply(giantScale));
        ModelLayers.GIANT_ARMOR.putFrom(humanoidArmor.map(layer -> layer.apply(giantScale)), (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.GLOW_SQUID, (Object)squidBodyLayer);
        result.put((Object)ModelLayers.GLOW_SQUID_BABY, (Object)squidBabyBodyLayer);
        result.put((Object)ModelLayers.GOAT, (Object)GoatModel.createBodyLayer());
        result.put((Object)ModelLayers.GOAT_BABY, (Object)BabyGoatModel.createBodyLayer());
        result.put((Object)ModelLayers.GUARDIAN, (Object)GuardianModel.createBodyLayer());
        result.put((Object)ModelLayers.HAPPY_GHAST, (Object)HappyGhastModel.createBodyLayer(false, CubeDeformation.NONE));
        result.put((Object)ModelLayers.HAPPY_GHAST_BABY, (Object)HappyGhastModel.createBodyLayer(true, CubeDeformation.NONE).apply(HappyGhastModel.BABY_TRANSFORMER));
        result.put((Object)ModelLayers.HAPPY_GHAST_HARNESS, (Object)HappyGhastHarnessModel.createHarnessLayer(false));
        result.put((Object)ModelLayers.HAPPY_GHAST_BABY_HARNESS, (Object)HappyGhastHarnessModel.createHarnessLayer(true).apply(HappyGhastModel.BABY_TRANSFORMER));
        result.put((Object)ModelLayers.HAPPY_GHAST_ROPES, (Object)HappyGhastModel.createBodyLayer(false, new CubeDeformation(0.2f)));
        result.put((Object)ModelLayers.HAPPY_GHAST_BABY_ROPES, (Object)HappyGhastModel.createBodyLayer(true, new CubeDeformation(0.2f)).apply(HappyGhastModel.BABY_TRANSFORMER));
        result.put((Object)ModelLayers.HOGLIN, (Object)hoglinLayer);
        result.put((Object)ModelLayers.HOGLIN_BABY, (Object)hoglinBabyLayer);
        result.put((Object)ModelLayers.HOPPER_MINECART, (Object)minecartBodyLayer);
        MeshTransformer livingHorseScale = MeshTransformer.scaling(1.1f);
        result.put((Object)ModelLayers.HORSE, (Object)horseBodyLayer.apply(livingHorseScale));
        result.put((Object)ModelLayers.HORSE_BABY, (Object)horseBabyLayer.apply(livingHorseScale));
        result.put((Object)ModelLayers.HORSE_ARMOR, (Object)LayerDefinition.create(AbstractEquineModel.createBodyMesh(new CubeDeformation(0.1f)), 64, 64).apply(livingHorseScale));
        result.put((Object)ModelLayers.HORSE_SADDLE, (Object)horseSaddleLayer.apply(livingHorseScale));
        MeshTransformer huskScale = MeshTransformer.scaling(1.0625f);
        result.put((Object)ModelLayers.HUSK, (Object)humanoidBodyLayer.apply(huskScale));
        ModelLayers.HUSK_ARMOR.putFrom(humanoidArmor.map(layer -> layer.apply(huskScale)), (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.HUSK_BABY, (Object)babyZombieLayer);
        ModelLayers.HUSK_BABY_ARMOR.putFrom(humanoidBabyArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.ILLUSIONER, (Object)illagerBodyLayer);
        result.put((Object)ModelLayers.IRON_GOLEM, (Object)IronGolemModel.createBodyLayer());
        result.put((Object)ModelLayers.LEASH_KNOT, (Object)LeashKnotModel.createBodyLayer());
        result.put((Object)ModelLayers.LLAMA, (Object)llamaBodyLayer);
        result.put((Object)ModelLayers.LLAMA_BABY, (Object)llamaBabyBodyLayer);
        result.put((Object)ModelLayers.LLAMA_DECOR, (Object)llamaDecorLayer);
        result.put((Object)ModelLayers.LLAMA_BABY_DECOR, (Object)llamaBabyDecorLayer);
        result.put((Object)ModelLayers.LLAMA_SPIT, (Object)LlamaSpitModel.createBodyLayer());
        result.put((Object)ModelLayers.MAGMA_CUBE, (Object)MagmaCubeModel.createBodyLayer());
        result.put((Object)ModelLayers.MINECART, (Object)minecartBodyLayer);
        result.put((Object)ModelLayers.MOOSHROOM, (Object)cowBodyLayer);
        result.put((Object)ModelLayers.MOOSHROOM_BABY, (Object)BabyCowModel.createBodyLayer());
        result.put((Object)ModelLayers.MULE, (Object)DonkeyModel.createBodyLayer(0.92f));
        result.put((Object)ModelLayers.MULE_BABY, (Object)BabyDonkeyModel.createBabyLayer());
        result.put((Object)ModelLayers.MULE_SADDLE, (Object)DonkeyModel.createSaddleLayer(0.92f));
        result.put((Object)ModelLayers.NAUTILUS, (Object)NautilusModel.createBodyLayer());
        result.put((Object)ModelLayers.NAUTILUS_BABY, (Object)NautilusModel.createBabyBodyLayer());
        result.put((Object)ModelLayers.NAUTILUS_SADDLE, (Object)nautilusSaddleLayer);
        result.put((Object)ModelLayers.NAUTILUS_ARMOR, (Object)NautilusArmorModel.createBodyLayer());
        result.put((Object)ModelLayers.ZOMBIE_NAUTILUS, (Object)NautilusModel.createBodyLayer());
        result.put((Object)ModelLayers.ZOMBIE_NAUTILUS_CORAL, (Object)ZombieNautilusCoralModel.createBodyLayer());
        result.put((Object)ModelLayers.OCELOT, (Object)felineBodyLayer);
        result.put((Object)ModelLayers.OCELOT_BABY, (Object)felineBabyBodyLayer);
        result.put((Object)ModelLayers.PANDA, (Object)pandaBodyLayer);
        result.put((Object)ModelLayers.PANDA_BABY, (Object)pandaBabyBodyLayer);
        result.put((Object)ModelLayers.PARCHED, (Object)SkeletonModel.createSingleModelDualBodyLayer());
        ModelLayers.PARCHED_ARMOR.putFrom(humanoidArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.PARCHED_OUTER_LAYER, (Object)LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25f), 0.0f), 64, 32));
        result.put((Object)ModelLayers.PARROT, (Object)ParrotModel.createBodyLayer());
        result.put((Object)ModelLayers.PHANTOM, (Object)PhantomModel.createBodyLayer());
        result.put((Object)ModelLayers.PIG, (Object)pigBodyLayer);
        result.put((Object)ModelLayers.PIG_BABY, (Object)BabyPigModel.createBodyLayer(CubeDeformation.NONE));
        result.put((Object)ModelLayers.PIG_SADDLE, (Object)pigSaddleLayer);
        result.put((Object)ModelLayers.PIGLIN, (Object)piglinLayer);
        ModelLayers.PIGLIN_ARMOR.putFrom(piglinArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.PIGLIN_BRUTE, (Object)piglinLayer);
        ModelLayers.PIGLIN_BRUTE_ARMOR.putFrom(piglinArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.PIGLIN_BABY, (Object)BabyPiglinModel.createBodyLayer());
        ModelLayers.PIGLIN_BABY_ARMOR.putFrom(piglinBabyArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.PIGLIN_HEAD, (Object)piglinHeadLayer);
        result.put((Object)ModelLayers.PILLAGER, (Object)illagerBodyLayer);
        result.put((Object)ModelLayers.PLAYER, (Object)LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, false), 64, 64));
        result.put((Object)ModelLayers.PLAYER_EARS, (Object)PlayerEarsModel.createEarsLayer());
        result.put((Object)ModelLayers.PLAYER_CAPE, (Object)PlayerCapeModel.createCapeLayer());
        result.put((Object)ModelLayers.PLAYER_HEAD, (Object)humanoidHeadLayer);
        ModelLayers.PLAYER_ARMOR.putFrom(playerArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.PLAYER_SLIM, (Object)LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, true), 64, 64));
        ModelLayers.PLAYER_SLIM_ARMOR.putFrom(playerArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.PLAYER_SPIN_ATTACK, (Object)SpinAttackEffectModel.createLayer());
        result.put((Object)ModelLayers.POLAR_BEAR, (Object)PolarBearModel.createBodyLayer());
        result.put((Object)ModelLayers.POLAR_BEAR_BABY, (Object)BabyPolarBearModel.createBodyLayer());
        result.put((Object)ModelLayers.PUFFERFISH_BIG, (Object)PufferfishBigModel.createBodyLayer());
        result.put((Object)ModelLayers.PUFFERFISH_MEDIUM, (Object)PufferfishMidModel.createBodyLayer());
        result.put((Object)ModelLayers.PUFFERFISH_SMALL, (Object)PufferfishSmallModel.createBodyLayer());
        result.put((Object)ModelLayers.RABBIT, (Object)AdultRabbitModel.createBodyLayer());
        result.put((Object)ModelLayers.RABBIT_BABY, (Object)BabyRabbitModel.createBodyLayer());
        result.put((Object)ModelLayers.RAVAGER, (Object)RavagerModel.createBodyLayer());
        result.put((Object)ModelLayers.SALMON, (Object)salmonBodyLayer);
        result.put((Object)ModelLayers.SALMON_SMALL, (Object)salmonBodyLayer.apply(SalmonModel.SMALL_TRANSFORMER));
        result.put((Object)ModelLayers.SALMON_LARGE, (Object)salmonBodyLayer.apply(SalmonModel.LARGE_TRANSFORMER));
        result.put((Object)ModelLayers.SHEEP, (Object)sheepBodyLayer);
        result.put((Object)ModelLayers.SHEEP_BABY, (Object)sheepBabyBodyLayer);
        result.put((Object)ModelLayers.SHEEP_WOOL, (Object)sheepWoolLayer);
        result.put((Object)ModelLayers.SHEEP_BABY_WOOL, (Object)sheepBabyBodyLayer);
        result.put((Object)ModelLayers.SHEEP_WOOL_UNDERCOAT, (Object)sheepBodyLayer);
        result.put((Object)ModelLayers.SHIELD, (Object)ShieldModel.createLayer());
        result.put((Object)ModelLayers.SHULKER, (Object)ShulkerModel.createBodyLayer());
        result.put((Object)ModelLayers.SHULKER_BOX, (Object)ShulkerModel.createBoxLayer());
        result.put((Object)ModelLayers.SHULKER_BULLET, (Object)ShulkerBulletModel.createBodyLayer());
        result.put((Object)ModelLayers.SILVERFISH, (Object)SilverfishModel.createBodyLayer());
        result.put((Object)ModelLayers.SKELETON, (Object)skeletonBodyLayer);
        ModelLayers.SKELETON_ARMOR.putFrom(humanoidArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.SKELETON_HORSE, (Object)horseBodyLayer);
        result.put((Object)ModelLayers.SKELETON_HORSE_BABY, (Object)horseBabyLayer);
        result.put((Object)ModelLayers.SKELETON_HORSE_SADDLE, (Object)horseSaddleLayer);
        result.put((Object)ModelLayers.SKELETON_SKULL, (Object)mobHeadLayer);
        result.put((Object)ModelLayers.SLIME, (Object)SlimeModel.createInnerBodyLayer());
        result.put((Object)ModelLayers.SLIME_OUTER, (Object)SlimeModel.createOuterBodyLayer());
        result.put((Object)ModelLayers.SNIFFER, (Object)snifferBodyLayer);
        result.put((Object)ModelLayers.SNIFFER_BABY, (Object)snifferBabyBodyLayer);
        result.put((Object)ModelLayers.SNOW_GOLEM, (Object)SnowGolemModel.createBodyLayer());
        result.put((Object)ModelLayers.SPAWNER_MINECART, (Object)minecartBodyLayer);
        result.put((Object)ModelLayers.SPIDER, (Object)spiderBodyLayer);
        result.put((Object)ModelLayers.SQUID, (Object)squidBodyLayer);
        result.put((Object)ModelLayers.SQUID_BABY, (Object)squidBabyBodyLayer);
        result.put((Object)ModelLayers.STRAY, (Object)skeletonBodyLayer);
        ModelLayers.STRAY_ARMOR.putFrom(humanoidArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.STRAY_OUTER_LAYER, (Object)LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25f), 0.0f), 64, 32));
        result.put((Object)ModelLayers.STRIDER, (Object)striderLayer);
        result.put((Object)ModelLayers.STRIDER_SADDLE, (Object)striderLayer);
        result.put((Object)ModelLayers.STRIDER_BABY, (Object)striderBabyLayer);
        result.put((Object)ModelLayers.TADPOLE, (Object)TadpoleModel.createBodyLayer());
        result.put((Object)ModelLayers.TNT_MINECART, (Object)minecartBodyLayer);
        result.put((Object)ModelLayers.TRADER_LLAMA, (Object)llamaBodyLayer);
        result.put((Object)ModelLayers.TRADER_LLAMA_BABY, (Object)llamaBabyBodyLayer);
        result.put((Object)ModelLayers.TRIDENT, (Object)TridentModel.createLayer());
        result.put((Object)ModelLayers.TROPICAL_FISH_LARGE, (Object)TropicalFishLargeModel.createBodyLayer(CubeDeformation.NONE));
        result.put((Object)ModelLayers.TROPICAL_FISH_LARGE_PATTERN, (Object)TropicalFishLargeModel.createBodyLayer(FISH_PATTERN_DEFORMATION));
        result.put((Object)ModelLayers.TROPICAL_FISH_SMALL, (Object)TropicalFishSmallModel.createBodyLayer(CubeDeformation.NONE));
        result.put((Object)ModelLayers.TROPICAL_FISH_SMALL_PATTERN, (Object)TropicalFishSmallModel.createBodyLayer(FISH_PATTERN_DEFORMATION));
        result.put((Object)ModelLayers.TURTLE, (Object)turtleBodyLayer);
        result.put((Object)ModelLayers.TURTLE_BABY, (Object)BabyTurtleModel.createBodyLayer());
        result.put((Object)ModelLayers.UNDEAD_HORSE_ARMOR, (Object)LayerDefinition.create(AbstractEquineModel.createBodyMesh(new CubeDeformation(0.1f)), 64, 64));
        result.put((Object)ModelLayers.VEX, (Object)VexModel.createBodyLayer());
        result.put((Object)ModelLayers.VILLAGER, (Object)villagerBodyLayer);
        result.put((Object)ModelLayers.VILLAGER_NO_HAT, (Object)villagerNoHatLayer);
        result.put((Object)ModelLayers.VILLAGER_BABY, (Object)villagerBabyLayer);
        result.put((Object)ModelLayers.VILLAGER_BABY_NO_HAT, (Object)villagerBabyNoHatLayer);
        result.put((Object)ModelLayers.VINDICATOR, (Object)illagerBodyLayer);
        result.put((Object)ModelLayers.WARDEN, (Object)WardenModel.createBodyLayer());
        result.put((Object)ModelLayers.WARDEN_TENDRILS, (Object)WardenModel.createTendrilsLayer());
        result.put((Object)ModelLayers.WARDEN_HEART, (Object)WardenModel.createHeartLayer());
        result.put((Object)ModelLayers.WARDEN_BIOLUMINESCENT, (Object)WardenModel.createBioluminescentLayer());
        result.put((Object)ModelLayers.WARDEN_PULSATING_SPOTS, (Object)WardenModel.createPulsatingSpotsLayer());
        result.put((Object)ModelLayers.WARM_COW, (Object)warmCowBodyLayer);
        result.put((Object)ModelLayers.WARM_COW_BABY, (Object)BabyCowModel.createBodyLayer());
        result.put((Object)ModelLayers.WANDERING_TRADER, (Object)villagerBodyLayer);
        result.put((Object)ModelLayers.WIND_CHARGE, (Object)WindChargeModel.createBodyLayer());
        result.put((Object)ModelLayers.WITCH, (Object)WitchModel.createBodyLayer().apply(villagerLikeScale));
        result.put((Object)ModelLayers.WITHER, (Object)WitherBossModel.createBodyLayer(CubeDeformation.NONE));
        result.put((Object)ModelLayers.WITHER_ARMOR, (Object)WitherBossModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
        result.put((Object)ModelLayers.WITHER_SKULL, (Object)WitherSkullRenderer.createSkullLayer());
        MeshTransformer witherSkeletonScale = MeshTransformer.scaling(1.2f);
        result.put((Object)ModelLayers.WITHER_SKELETON, (Object)skeletonBodyLayer.apply(witherSkeletonScale));
        ModelLayers.WITHER_SKELETON_ARMOR.putFrom(humanoidArmor.map(layer -> layer.apply(witherSkeletonScale)), (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.WITHER_SKELETON_SKULL, (Object)mobHeadLayer);
        result.put((Object)ModelLayers.WOLF, (Object)wolfBodyLayer);
        result.put((Object)ModelLayers.WOLF_ARMOR, (Object)wolfArmorLayer);
        result.put((Object)ModelLayers.WOLF_BABY, (Object)BabyWolfModel.createBodyLayer());
        result.put((Object)ModelLayers.ZOGLIN, (Object)hoglinLayer);
        result.put((Object)ModelLayers.ZOGLIN_BABY, (Object)hoglinBabyLayer);
        result.put((Object)ModelLayers.ZOMBIE, (Object)humanoidBodyLayer);
        ModelLayers.ZOMBIE_ARMOR.putFrom(humanoidArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.ZOMBIE_BABY, (Object)babyZombieLayer);
        ModelLayers.ZOMBIE_BABY_ARMOR.putFrom(humanoidBabyArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.ZOMBIE_HEAD, (Object)humanoidHeadLayer);
        result.put((Object)ModelLayers.ZOMBIE_HORSE, (Object)horseBodyLayer);
        result.put((Object)ModelLayers.ZOMBIE_HORSE_BABY, (Object)horseBabyLayer);
        result.put((Object)ModelLayers.ZOMBIE_HORSE_SADDLE, (Object)horseSaddleLayer);
        result.put((Object)ModelLayers.ZOMBIE_VILLAGER, (Object)zombieVillagerBodyLayer);
        result.put((Object)ModelLayers.ZOMBIE_VILLAGER_NO_HAT, (Object)zombieVillagerNoHatLayer);
        ArmorModelSet<LayerDefinition> zombieVillagerArmor = ZombieVillagerModel.createArmorLayerSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION);
        ModelLayers.ZOMBIE_VILLAGER_ARMOR.putFrom(zombieVillagerArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.ZOMBIE_VILLAGER_BABY, (Object)babyZombieVillagerBodyLayer);
        result.put((Object)ModelLayers.ZOMBIE_VILLAGER_BABY_NO_HAT, (Object)babyZombieVillagerNoHatLayer);
        ModelLayers.ZOMBIE_VILLAGER_BABY_ARMOR.putFrom(ZombieVillagerModel.createBabyArmorMeshSet(BABY_INNER_ARMOR_DEFORMATION, BABY_OUTER_ARMOR_DEFORMATION, PartPose.ZERO).map(mesh -> LayerDefinition.create(mesh, 64, 64)), (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.ZOMBIFIED_PIGLIN, (Object)AdultZombifiedPiglinModel.createBodyLayer());
        ModelLayers.ZOMBIFIED_PIGLIN_ARMOR.putFrom(piglinArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.ZOMBIFIED_PIGLIN_BABY, (Object)BabyZombifiedPiglinModel.createBodyLayer());
        ModelLayers.ZOMBIFIED_PIGLIN_BABY_ARMOR.putFrom(piglinBabyArmor, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)result);
        result.put((Object)ModelLayers.BAMBOO_RAFT, (Object)RaftModel.createRaftModel());
        result.put((Object)ModelLayers.BAMBOO_CHEST_RAFT, (Object)RaftModel.createChestRaftModel());
        LayerDefinition boatModel = BoatModel.createBoatModel();
        LayerDefinition chestBoatModel = BoatModel.createChestBoatModel();
        result.put((Object)ModelLayers.OAK_BOAT, (Object)boatModel);
        result.put((Object)ModelLayers.OAK_CHEST_BOAT, (Object)chestBoatModel);
        result.put((Object)ModelLayers.SPRUCE_BOAT, (Object)boatModel);
        result.put((Object)ModelLayers.SPRUCE_CHEST_BOAT, (Object)chestBoatModel);
        result.put((Object)ModelLayers.BIRCH_BOAT, (Object)boatModel);
        result.put((Object)ModelLayers.BIRCH_CHEST_BOAT, (Object)chestBoatModel);
        result.put((Object)ModelLayers.JUNGLE_BOAT, (Object)boatModel);
        result.put((Object)ModelLayers.JUNGLE_CHEST_BOAT, (Object)chestBoatModel);
        result.put((Object)ModelLayers.ACACIA_BOAT, (Object)boatModel);
        result.put((Object)ModelLayers.ACACIA_CHEST_BOAT, (Object)chestBoatModel);
        result.put((Object)ModelLayers.CHERRY_BOAT, (Object)boatModel);
        result.put((Object)ModelLayers.CHERRY_CHEST_BOAT, (Object)chestBoatModel);
        result.put((Object)ModelLayers.DARK_OAK_BOAT, (Object)boatModel);
        result.put((Object)ModelLayers.DARK_OAK_CHEST_BOAT, (Object)chestBoatModel);
        result.put((Object)ModelLayers.PALE_OAK_BOAT, (Object)boatModel);
        result.put((Object)ModelLayers.PALE_OAK_CHEST_BOAT, (Object)chestBoatModel);
        result.put((Object)ModelLayers.MANGROVE_BOAT, (Object)boatModel);
        result.put((Object)ModelLayers.MANGROVE_CHEST_BOAT, (Object)chestBoatModel);
        LayerDefinition standingSignModel = StandingSignRenderer.createSignLayer(true);
        LayerDefinition wallSignModel = StandingSignRenderer.createSignLayer(false);
        WoodType.values().forEach(woodType -> {
            result.put((Object)ModelLayers.createStandingSignModelName(woodType), (Object)standingSignModel);
            result.put((Object)ModelLayers.createWallSignModelName(woodType), (Object)wallSignModel);
            for (HangingSignBlock.Attachment attachmentType : HangingSignBlock.Attachment.values()) {
                LayerDefinition hangingSignModel = HangingSignRenderer.createHangingSignLayer(attachmentType);
                result.put((Object)ModelLayers.createHangingSignModelName(woodType, attachmentType), (Object)hangingSignModel);
            }
        });
        ImmutableMap definitions = result.build();
        List<ModelLayerLocation> missingDefinitions = ModelLayers.getKnownLocations().filter(l -> !definitions.containsKey(l)).toList();
        if (!missingDefinitions.isEmpty()) {
            throw new IllegalStateException("Missing layer definitions: " + String.valueOf(missingDefinitions));
        }
        return definitions;
    }
}

